
@hostname = metro-backend-ohx3vk2ipa-ew.a.run.app
@contentType = application/json
@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJvYXQiOjE2NDIwNjIyNjEsImlhdCI6MTY0MjA2MjI2MSwiZXhwIjoxNjQyNjY3MDYxLCJhdWQiOiJodHRwczovL3lvdXJkb21haW4uY29tIiwiaXNzIjoiZmVhdGhlcnMiLCJzdWIiOiI2MWRjNDc3OTFmZDM0ZTg3MWQ2YWJlOTMiLCJqdGkiOiI5YWNiZGViMy04ZmZkLTQ3YzMtYjA4ZC0xMjU3YWNjY2JmZWUifQ.7rgXEEeIcVW3g3aNeHq7YQKjKnizSXd9UqJo3Bq_jxQ
@email = "fixiv59040@rubygon.com"
@password = "5656"
@postmanlink  = https://www.getpostman.com/collections/011abae26ecba7e10682

# register
POST https://{{hostname}}/users
content-type: {{contentType}}

{
"email": {{email}},
"password": {{password}},
"firstName": "firstName",
"lastName": "lastName"
}
###
# login
POST https://{{hostname}}/authentication 
content-type: {{contentType}}

{
"email": {{email}},
"password": {{password}},
"strategy": "local"
}
###
# 2ways verification
POST https://{{hostname}}/authmanagement
content-type: {{contentType}}
Authorization: {{authorization}}

{
"action": "verifySignupShort",
"value": {"user":{"email": {{email}}}, "token": "410565"}
}
###
# 2ways verification resend
POST https://{{hostname}}/authmanagement
content-type: {{contentType}}
Authorization: {{authorization}}

{
    "action": "resendVerifySignup",
    "value": {"email": {{email}}}
}
###
# Reset Password
POST https://{{hostname}}/authmanagement
content-type: {{contentType}}
Authorization: {{authorization}}

{
   "action": "sendResetPwd",   
   "value": { "email": {{email}}}
}
###
# Create role
POST https://{{hostname}}/roles
content-type: {{contentType}}
Authorization: {{authorization}}

{    
    "name": "METRO_AREA_OWNER",    
    "displayName": "Area Owner",    
    "description": "Owner of the area"
}
###
# Get all areas
GET https://{{hostname}}/area
content-type: {{contentType}}
Authorization: {{authorization}}

###
# Create new area
POST https://{{hostname}}/area
content-type: {{contentType}}
Authorization: {{authorization}}

{    
    "name": "Ashkelon"    
}
###
# Get one area
GET https://{{hostname}}/area/61d2e959927d2b5be84b2ce1
content-type: {{contentType}}
Authorization: {{authorization}}
###
# Get all area - paginate
GET https://{{hostname}}/area?$limit=100&$skip=0
content-type: {{contentType}}
Authorization: {{authorization}}
###
# Get all autorities
GET https://{{hostname}}/authorities?areaId=61d2e93c927d2b5be84b2cdb
content-type: {{contentType}}
Authorization: {{authorization}}
###
# Create new Authority
POST https://{{hostname}}/authorities
content-type: {{contentType}}
Authorization: {{authorization}}

{  
    "areaId": "61d2e93c927d2b5be84b2cdb",  
    "name": "שומרון", 
    "email": "contact@email.com", 
    "address": "השונית 3"
}
###
# Upload file 
GET https://{{hostname}}/
content-type: {{contentType}}
Authorization: {{authorization}}
###
# Get all businesses in specific autority
GET https://{{hostname}}/business?autorityId=61d2eb2df58fa2f89374dbb7
content-type: {{contentType}}
Authorization: {{authorization}}
###
# Create new business
POST  https://{{hostname}}/business
content-type: {{contentType}}
Authorization: {{authorization}}

{
   "name":"עין חרא",
   "description":"בואו לטייל בעין חרא עוד היום",
   "status":"PENDING_APPROVAL",
   "tagsIds":["food"],
   "autorityId":"61d2eb2df58fa2f89374dbb7",
   "address":"ליד עזאזל בדרך לקנטים",
   "phoneNumber":"0566296634",
   "contactPersonName":"כלב בן יפונה",
   "contactPersonPhoneNumber":"0566296634",
   "emailAddress":"hara@gmail.com",
   "relevantTo":"GOLDEN_AGE",
   "websiteUrl":"www.website.com",
   "facebookPageUrl":"www.website.com",
   "instagramPageUrl":"www.website.com",
   "youtubePageUrl":"www.website.com",
   "twitterPageUrl":"www.website.com",
   "linkedInPageUrl":"www.website.com",
   "galleryFileIds":[
      "image1",
      "image2"
   ],
   "openingHours":{
      "sunday":{
         "start":"08:00",
         "end":"16:00"
      },
      "monday":{
         "start":"08:00",
         "end":"16:00"
      },
      "tuesday":{
         "start":"08:00",
         "end":"16:00"
      },
      "wednesday":{
         "start":"08:00",
         "end":"16:00"
      },
      "thursday":{
         "start":"08:00",
         "end":"16:00"
      },
      "friday":{
         "start":"08:00",
         "end":"16:00"
      },
      "saturday":{
         "start":"08:00",
         "end":"16:00"
      }
   },
   "open24Hours":false
}



#   {
#       name: { type: String, required: true },
#       description: { type: String, required: true },
#       status: { type: String, enum: ["PUBLIC", "PRIVATE", "PENDING_APPROVAL"] },
#       tagsIds: { type: [String], default: [] },
#       userId: { type: String, required: true },
#       autorityId: { type: String, required: true },
#       address: { type: String },
#       phoneNumber: { type: String },
#       contactPersonName: { type: String },
#       contactPersonPhoneNumber: { type: String },
#       websiteUrl: { type: String },
#       emailAddress: { type: String },
#       relevantTo: {
#         type: String,
#         enum: ["INFANCY", "KIDS&YOUTH", "ALL_FAMILY", "GROUPS", "GOLDEN_AGE"],
#         required: true,
#       },
#       facebookPageUrl: { type: String },
#       instagramPageUrl: { type: String },
#       youtubePageUrl: { type: String },
#       twitterPageUrl: { type: String },
#       linkedInPageUrl: { type: String },
#       galleryFileIds: { type: [String], default: [] },
#       openingHours: {
#         type: Map,
#         default: {},
#       },
#       open24Hours: { type: Boolean, default: false },
#     },
#     {
#       timestamps: true,
#     }