
@hostname = metro-backend-ohx3vk2ipa-ew.a.run.app
@contentType = application/json
@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJvYXQiOjE2NDE0ODI3NDYsImlhdCI6MTY0MTQ4Mjc0NiwiZXhwIjoxNjQyMDg3NTQ2LCJhdWQiOiJodHRwczovL3lvdXJkb21haW4uY29tIiwiaXNzIjoiZmVhdGhlcnMiLCJzdWIiOiI2MWQ3MDlmMWRmZmQ1MWQ2MTI1MmUyZTciLCJqdGkiOiIzMmU3NzVhNy0wN2JlLTRmNmItYjU1Ni04MTBhMGQyMTAwN2UifQ.5NqC3DmzI2AORHGqxrBNAhbub5s0jDcDTWSDIh3mrnU

@email = "vapev86956@upsdom.com"
@password = "12345678"
@postmanlink  = https://www.getpostman.com/collections/011abae26ecba7e10682

# register
POST https://{{hostname}}/users
content-type: {{contentType}}

{
"email": {{email}},
"password": {{password}},
"firstName": "firstName",
"lastName": "lastName"
}
###
# login
POST https://{{hostname}}/authentication 
content-type: {{contentType}}

{
"email": {{email}},
"password": {{password}},
"strategy": "local"
}
###
# 2ways verification
POST https://{{hostname}}/authmanagement
content-type: {{contentType}}
Authorization: {{authorization}}

{
"action": "verifySignupShort",
"value": {"user":{"email": {{email}}}, "token": "410565"}
}
###
# 2ways verification resend
POST https://{{hostname}}/authmanagement
content-type: {{contentType}}
Authorization: {{authorization}}

{
    "action": "resendVerifySignup",
    "value": {"email": {{email}}}
}
###
# Reset Password
POST https://{{hostname}}/authmanagement
content-type: {{contentType}}
Authorization: {{authorization}}

{
   "action": "sendResetPwd",   
   "value": { "email": {{email}}}
}
###
# Create role
POST https://{{hostname}}/roles
content-type: {{contentType}}
Authorization: {{authorization}}

{    
    "name": "METRO_AREA_OWNER",    
    "displayName": "Area Owner",    
    "description": "Owner of the area"
}
###
# Get all areas
GET https://{{hostname}}/area
content-type: {{contentType}}
Authorization: {{authorization}}

{    
    "email": {{email}},    
    "password": {{password}},   
    "firstName": "firstName",
    "lastName": "lastName"
}
###
# Create new area
POST https://{{hostname}}/area
content-type: {{contentType}}
Authorization: {{authorization}}

{    
    "name": "Herzelia"    
}
###
# Get one area
POST https://{{hostname}}/area
content-type: {{contentType}}
Authorization: {{authorization}}

{    
 "email": "jedecen822@zoeyy.com",    
 "password": "1a2a3a",    
 "firstName": "Ran",   
 "lastName": "Hassid"
}
