
@localhost = localhost
@port = 3030
@host = {{localhost}}:{{port}}
@contentType = application/json
@authorization = 'token eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJvYXQiOjE2NDEzMDAxNzAsImlhdCI6MTY0MTMwMDE2OSwiZXhwIjoxNjQxOTA0OTY5LCJhdWQiOiJodHRwczovL3lvdXJkb21haW4uY29tIiwiaXNzIjoiZmVhdGhlcnMiLCJzdWIiOiI2MWQ0NDBiNzVjNmZhYzRkMTBmMWVkMzciLCJqdGkiOiI2ZTg3YmZlYy1jMzljLTRkOWItOWVhNS05MTY1ZDVhYWFlYzcifQ.DeaNTGbDPUjLgpW9f6wQZRYymyb7ny54qN4cS9s0gyw'

@email = "yoxir27636@veb65.com"
@password = "12345678"

###
POST http://{{host}}/authentication 
content-type: {{contentType}}

{
"email": {{email}},
"password": {{password}},
"strategy": "local"
}

###
POST http://{{host}}/users
content-type: {{contentType}}

{
"email": {{email}},
"password": {{password}},
"firstName": "firstName",
"lastName": "lastName"
}

###
POST http://{{host}}/users
content-type: {{contentType}}
Authorization: {{authorization}}

{
"action": "resendVerifySignup",
"value": {"email": {{email}}}
}
