

POST https://metro-backend-ohx3vk2ipa-ew.a.run.app/authentication 
content-type: application/json

{
"email": "vexot77202@xxyxi.com",
"password": "12345678",
"strategy": "local"
}

###

POST https://metro-backend-ohx3vk2ipa-ew.a.run.app/users
content-type: application/json

{
"email": "vexot77202@xxyxi.com",
"password": "12345678",
"firstName": "tester",
"lastName": "tester"
}

###

POST https://metro-backend-ohx3vk2ipa-ew.a.run.app/verification
content-type: application/json
Authorization: token xxx

{
"email": "vexot77202@xxyxi.com",
"password": "12345678",
"firstName": "tester",
"lastName": "tester"
}

###

GET  http://10.0.0.11:3030/health